---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.demo.kcd.io
  resources:
  - demoresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.kcd.io
  resources:
  - demoresources/finalizers
  verbs:
  - update
- apiGroups:
  - demo.demo.kcd.io
  resources:
  - demoresources/status
  verbs:
  - get
  - patch
  - update
